### ISSUE TITLE
Describe.only ignored

### ISSUE THREAD

**Issue by atav32** [webdriverio/wdio-mocha-framework#77] opened 2017-07-27 19:00 UTC
For some reason, `describe.only()` and `it.only()` are being ignored and I can't run isolated tests.

**Comment by christian-bromann** [comment] 2017-07-27 20:39
If you want to run a specific test spec use `--spec path/to/test.js`. The launcher can't look into the files before launching the processes.

Duplicate of webdriverio/webdriverio#1247

**Closed by christian-bromann** 2017-07-27 20:39 UTC
